### ISSUE TITLE
Add branches for starter projects

### ISSUE THREAD

**Issue by mroswell** [pinax/pinax-starter-projects#1]
social
social-auth
lms
forums
waiting-list
private-beta
symposion

**Comment by paltman** [comment]
I think we should break this into individual issues, one per starter project

**Comment by ossanna16** [comment]
@paltman Can this issue be closed since we have new issues for this now?

**Comment by jtauber** [comment]
It's still nice to have one place to see overall status. I'd keep it open until the "children" are all done.

**Comment by ossanna16** [comment]
👍

**Comment by paltman** [comment]
I'm actually going to convert this to a milestone rather than an issue as that is really what this is now.
