### ISSUE TITLE
Should _account_bar.html exist in pinax-blog starter?

### ISSUE THREAD

**Issue by easton402** [pinax/pinax-starter-projects#17]
The pinax starter for pinax-blog contains some html files. I guess that suggests users to customise their own _account_bar, _footer, _scripts, _styles. But I think it's a bad idea to put them there holding place, because these html files can be found by `TEMPLATE_LOADERS` ahead of those in pinax_theme_bootstrap directory, then affect all pages. 
This is what I know about starter for pinax-blog, I don't know if this is common among other starters.

**Comment by jtauber** [comment]
The pinax-blog starter project doesn't have user accounts and so the default _account_bar provided by pinax-theme-bootstrap isn't appropriate, so we override it with nothing.

The fact it is ahead of pinax-theme-bootstrap and overrides the one there is intended.
