### ISSUE TITLE
Update documents starter project for outlined changes in pinax-documents

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-starter-projects#18]
After the following issues are done in `pinax-documents`, update the starter project with the new release:

* [#8 Move post_save receiver to receivers.py](https://github.com/pinax/pinax-documents/issues/8)
* [#7 Add HookSets](https://github.com/pinax/pinax-documents/issues/7)
* [#6 Update all urls with the pinax prefix](https://github.com/pinax/pinax-documents/issues/6)
* [#5 Rewrite views as class based views](https://github.com/pinax/pinax-documents/issues/5)
* [#4 All templates should be under `pinax/documents/`](https://github.com/pinax/pinax-documents/issues/4)
* [#3 Implement document deletion](https://github.com/pinax/pinax-documents/issues/3)

HINT: It's probably easier to make all the above updates in context of updating an instance of the starter project.  What'd I'd do is create an instance of the project, add it to git and commit.  That way you can more easily track the changes you make to it as you update it for the new app.

**Comment by grahamu** [comment]
Dev note: Document deletion requires a new template: pinax/documents/document_confirm_delete.html.
